name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Required to post comments
      pull-requests: write # Recommended for PR-related actions
      contents: read # Needed for checkout and diff
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh || { echo "Ollama install failed"; exit 1; }
          ollama serve &
          sleep 30
          curl http://127.0.0.1:11434 || { echo "Ollama server not running"; exit 1; }

      - name: Pull Code Llama Model
        run: |
          ollama pull codellama:7b-instruct || { echo "Model pull failed"; exit 1; }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install ollama gitpython

      - name: Get PR Diff
        id: get-diff
        run: |
          git fetch origin
          DIFF=$(git diff origin/main...HEAD)
          echo "PR_DIFF<<EOF" >> $GITHUB_ENV
          echo "$DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run Code Review
        run: python review_pr.py --github > review.md

      - name: Post Review as PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            });
